import { expect as baseExpect, test } from '@playwright/test';

const expect = baseExpect.configure({ timeout: 30_000 });

interface Inspection {
  mirrors3d: { id: string; parent: string; matrix: number[]; localMatrix: number[] }[];
  rearQuarters: { id: string; parent: string; matrix: number[]; localMatrix: number[] }[];
  rearPlateMatrix: number[];
  trim3d: { id: string; parent: string; matrix: number[]; localMatrix: number[]; pocketDepth: number }[];
  doors: Record<string, { open: number; window: number; target: number }>;
  doors3d: { id: string; angle: number; glassY: number; glassVisible: boolean; handle: number[] }[];
  hood: number; hatch: number; hoodAngle: number; hatchAngle: number; prop: boolean;
  propData: { deployed: boolean; length: number; base: number[]; tip: number[] };
  struts: { length: number; base: number[]; tip: number[] }[];
  output: { leftLow: boolean; low: boolean; high: boolean; position: boolean; brake: boolean; leftIndicator: boolean; rightIndicator: boolean; cabin: boolean; windowPower: boolean };
  lights: { name: string; intensity: number }[];
  locked: boolean; wiringVisible: boolean; cargo: boolean; elapsed: number; engineAngle: number;
}

test('Carroceria integrada portas vidros capo mala e eletrica', async ({ page }, testInfo) => {
  test.setTimeout(420_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/courses/injecao-eletronica-40h/lessons/aula-5-motor-completo');
  const canvas = page.locator('canvas[data-golf-canvas]');
  await expect(canvas).toBeVisible({ timeout: 30_000 });
  await page.getByRole('button', { name: 'Carroceria', exact: true }).click();
  await page.getByRole('button', { name: 'Pausar motor', exact: true }).click();
  const inspect = () => canvas.evaluate(element => (element as HTMLCanvasElement & { inspectBodyControl: () => Inspection }).inspectBodyControl());
  const step = async (seconds = 1) => { for (let second = 0; second < seconds; second++) await page.getByRole('button', { name: 'Avancar carroceria 1 s', exact: true }).click(); await canvas.evaluate(element => element.scrollIntoView({ block: 'center' })); };
  const capture = async (name: string) => { await canvas.evaluate(element => element.scrollIntoView({ block: 'center' })); expect(await canvas.evaluate(element => (element as HTMLCanvasElement & { inspectGolf: (pixels: boolean) => { contrastPixels: number } }).inspectGolf(true).contrastPixels)).toBeGreaterThan(100); await canvas.screenshot({ path: testInfo.outputPath(name) }); };
  const labels = ['dianteira esquerda', 'dianteira direita', 'traseira esquerda', 'traseira direita'];
  const initial = await inspect();
  for (const mirror of initial.mirrors3d) expect(mirror.parent).toBe(`golf-door-${mirror.id}`);
  for (const trim of initial.trim3d) {
    expect(trim.parent).toBe(`golf-door-${trim.id}`);
    expect(trim.pocketDepth).toBeCloseTo(120, 0);
  }
  const fit = () => canvas.evaluate(element => (element as HTMLCanvasElement & { inspectBodyFit: () => { clearance: number[]; hoodWidths: number[]; hoodMatrix: number[]; fenderMatrices: number[][] } }).inspectBodyFit());
  const initialFit = await fit();
  expect(initialFit.hoodWidths[0]).toBeGreaterThan(600);
  expect(initialFit.hoodWidths[0]).toBeLessThan(initialFit.hoodWidths[1] * 0.6);
  for (const quarter of initial.rearQuarters) expect(quarter.parent).toBe(`golf-door-${quarter.id}`);
  for (const clearance of initialFit.clearance) expect(clearance).toBeCloseTo(6, 0);
  for (const label of labels) await page.getByRole('button', { name: `Porta ${label}`, exact: true }).click();
  await step(2);
  await expect.poll(async () => (await inspect()).doors3d.map(door => Math.abs(door.angle)), { timeout: 30_000 }).toEqual([1.05, 1.05, 1.05, 1.05]);
  expect(Object.values((await inspect()).doors).every(door => door.open === 1)).toBe(true);
  expect((await inspect()).output.cabin).toBe(true);
  expect((await inspect()).doors3d.map(door => door.handle)).not.toEqual(initial.doors3d.map(door => door.handle));
  const openQuarters = (await inspect()).rearQuarters;
  const openMirrors = (await inspect()).mirrors3d;
  openMirrors.forEach((mirror, index) => {
    expect(mirror.matrix).not.toEqual(initial.mirrors3d[index].matrix);
    expect(mirror.localMatrix).toEqual(initial.mirrors3d[index].localMatrix);
  });
  openQuarters.forEach((quarter, index) => {
    expect(quarter.matrix).not.toEqual(initial.rearQuarters[index].matrix);
    expect(quarter.localMatrix).toEqual(initial.rearQuarters[index].localMatrix);
  });
  const openTrim = (await inspect()).trim3d;
  openTrim.forEach((trim, index) => {
    expect(trim.matrix).not.toEqual(initial.trim3d[index].matrix);
    expect(trim.localMatrix).toEqual(initial.trim3d[index].localMatrix);
    expect(trim.pocketDepth).toBeCloseTo(120, 0);
  });
  await page.getByRole('button', { name: 'Restaurar enquadramento', exact: true }).click();
  await capture('doors-open.png');
  await page.getByRole('combobox', { name: 'Vista externa', exact: true }).selectOption('side');
  await capture('cabin-seats-open-doors.png');
  await page.getByRole('combobox', { name: 'Vista externa', exact: true }).selectOption('interior');
  await capture('cabin-trim-interior.png');
  await page.getByRole('combobox', { name: 'Vista externa', exact: true }).selectOption('front');
  for (const label of labels) await page.getByRole('button', { name: `Baixar vidro ${label}`, exact: true }).click();
  await step(1);
  for (const door of (await inspect()).doors3d) {
    expect(door.glassVisible).toBe(true);
    expect(door.glassY).toBeCloseTo(-176, 3);
  }
  await capture('doors-windows-partial.png');
  expect((await inspect()).trim3d.map(trim => trim.matrix)).toEqual(openTrim.map(trim => trim.matrix));
  await step(2);
  await expect.poll(async () => (await inspect()).doors3d.every(door => !door.glassVisible && door.glassY === -440)).toBe(true);
  await capture('doors-windows-down.png');
  expect((await inspect()).rearQuarters).toEqual(openQuarters);
  expect((await inspect()).mirrors3d).toEqual(openMirrors);
  for (const label of labels) await page.getByRole('button', { name: `Subir vidro ${label}`, exact: true }).click();
  await page.getByRole('combobox', { name: 'Falha eletrica da carroceria', exact: true }).selectOption('comfort-fuse');
  await step(3); expect(Object.values((await inspect()).doors).every(door => door.window === 0)).toBe(true);
  await page.getByRole('combobox', { name: 'Falha eletrica da carroceria', exact: true }).selectOption('none');
  await step(3); expect(Object.values((await inspect()).doors).every(door => door.window === 1)).toBe(true);
  for (const label of labels) await page.getByRole('button', { name: `Porta ${label}`, exact: true }).click();
  await step(2);
  await page.getByRole('button', { name: 'Travar portas', exact: true }).click();
  expect((await inspect()).locked).toBe(true);
  await expect(page.getByRole('button', { name: 'Porta dianteira esquerda', exact: true })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Abrir porta-malas', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Destravar portas', exact: true }).click();
  await page.getByRole('button', { name: 'Liberar capo', exact: true }).click();
  await page.getByRole('button', { name: 'Abrir capo', exact: true }).click();
  await step(2);
  await page.getByRole('checkbox', { name: 'Vareta de sustentacao', exact: true }).check();
  await canvas.evaluate(element => element.scrollIntoView({ block: 'center' }));
  await expect.poll(async () => (await inspect()).propData.deployed).toBe(true);
  expect((await inspect()).hoodAngle).toBeCloseTo(1.05);
  expect((await fit()).hoodMatrix).not.toEqual(initialFit.hoodMatrix);
  expect((await fit()).fenderMatrices).toEqual(initialFit.fenderMatrices);
  await expect(page.getByRole('button', { name: 'Fechar capo', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Restaurar enquadramento', exact: true }).click();
  await capture('hood-prop.png');
  await page.getByRole('button', { name: 'Abrir porta-malas', exact: true }).click();
  await step(2);
  await page.getByRole('combobox', { name: 'Vista externa', exact: true }).selectOption('rear');
  await canvas.evaluate(element => element.scrollIntoView({ block: 'center' }));
  await expect.poll(async () => (await inspect()).hatchAngle).toBeCloseTo(-1.5);
  expect((await inspect()).rearPlateMatrix).toEqual(initial.rearPlateMatrix);
  expect((await inspect()).cargo).toBe(true);
  for (const clearance of (await fit()).clearance) expect(clearance).toBeCloseTo(6, 0);
  for (const strut of (await inspect()).struts) expect(strut.length).toBeGreaterThan(145);
  await capture('hatch-cargo.png');
  await page.getByRole('button', { name: 'Fechar porta-malas', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Vareta de sustentacao', exact: true }).uncheck();
  await page.getByRole('button', { name: 'Fechar capo', exact: true }).click();
  await step(2);
  await page.getByRole('combobox', { name: 'Comando dos farois', exact: true }).selectOption('low');
  await page.getByRole('checkbox', { name: 'Vista noturna', exact: true }).check();
  await page.getByRole('combobox', { name: 'Vista externa', exact: true }).selectOption('front');
  await canvas.evaluate(element => element.scrollIntoView({ block: 'center' }));
  await expect.poll(async () => (await inspect()).lights.filter(light => light.intensity > 0).length).toBe(2);
  await capture('headlights-low-night.png');
  const brightPixels = () => canvas.evaluate(element => (element as HTMLCanvasElement & { inspectGolf: () => { brightPixels: number } }).inspectGolf().brightPixels);
  const litPixels = await brightPixels();
  await page.getByRole('combobox', { name: 'Comando dos farois', exact: true }).selectOption('off');
  await canvas.evaluate(element => element.scrollIntoView({ block: 'center' }));
  await expect.poll(async () => (await inspect()).lights.every(light => light.intensity === 0)).toBe(true);
  expect(litPixels).toBeGreaterThan(await brightPixels() + 100);
  await page.getByRole('combobox', { name: 'Comando dos farois', exact: true }).selectOption('high');
  await canvas.evaluate(element => element.scrollIntoView({ block: 'center' }));
  await expect.poll(async () => (await inspect()).lights.filter(light => light.intensity > 0).length).toBe(4);
  await capture('headlights-high-night.png');
  await page.getByRole('combobox', { name: 'Falha eletrica da carroceria', exact: true }).selectOption('left-lamp-open');
  await canvas.evaluate(element => element.scrollIntoView({ block: 'center' }));
  await expect.poll(async () => (await inspect()).lights.filter(light => light.intensity > 0).length).toBe(2);
  expect((await inspect()).output.leftLow).toBe(false);
  await page.getByRole('combobox', { name: 'Falha eletrica da carroceria', exact: true }).selectOption('lighting-fuse');
  await canvas.evaluate(element => element.scrollIntoView({ block: 'center' }));
  await expect.poll(async () => (await inspect()).lights.every(light => light.intensity === 0)).toBe(true);
  expect((await inspect()).output.windowPower).toBe(true);
  await page.getByRole('combobox', { name: 'Falha eletrica da carroceria', exact: true }).selectOption('none');
  await page.getByRole('checkbox', { name: 'Pedal de freio acionado', exact: true }).check();
  expect((await inspect()).output.brake).toBe(true);
  await page.getByRole('combobox', { name: 'Estado de operacao', exact: true }).selectOption('off');
  expect((await inspect()).output.low).toBe(false);
  await page.getByRole('combobox', { name: 'Comando das setas', exact: true }).selectOption('hazard');
  const beforeBlink = (await inspect()).output.leftIndicator;
  await step(2); expect((await inspect()).output.leftIndicator).not.toBe(beforeBlink);
  await page.getByRole('combobox', { name: 'Vista externa', exact: true }).selectOption('rear');
  await capture('rear-lights.png');
  await page.getByRole('checkbox', { name: 'Vista noturna', exact: true }).uncheck();
  await page.getByRole('checkbox', { name: 'Mostrar chicote de carroceria', exact: true }).check();
  await page.getByRole('button', { name: 'Fantasma', exact: true }).click();
  await canvas.evaluate(element => element.scrollIntoView({ block: 'center' }));
  await expect.poll(async () => (await inspect()).wiringVisible).toBe(true);
  await capture('body-wiring.png');
  expect((await inspect()).engineAngle).toBe(initial.engineAngle);
  await page.getByRole('combobox', { name: 'Estado de operacao', exact: true }).selectOption('key');
  await page.getByRole('button', { name: 'Carro', exact: true }).click();
  await page.getByRole('button', { name: 'Porta dianteira direita', exact: true }).click();
  await page.getByRole('button', { name: 'Rodar motor', exact: true }).click();
  await canvas.evaluate(element => element.scrollIntoView({ block: 'center' }));
  await expect.poll(async () => (await inspect()).doors['front-right'].open, { timeout: 30_000 }).toBe(1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});