import { expect, test } from '@playwright/test';

interface FuelInspection {
  level: number; floatLevel: number; senderOhms: number; voltage: number; currentMa: number;
  decoded: number | null; indicated: number; reserveLamp: boolean; faultLamp: boolean; supply: boolean;
  elapsed: number; engineAngle: number; temperature: number; wipersElapsed: number; pumpPowered: boolean;
  floatPosition: number[]; floatAngle: number; needleRotation: number; liquidSurface: number;
  camera: number[]; projected: number[][]; wires: { name: string; from: number[]; to: number[] }[];
}

test('Combustivel: boia sinal instrumento reserva e falhas', async ({ page }, testInfo) => {
  test.setTimeout(180_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/courses/injecao-eletronica-40h/lessons/aula-5-motor-completo');
  const lab = page.locator('.golf-lab');
  const canvas = page.locator('canvas[data-golf-canvas]');
  await expect(canvas).toBeVisible({ timeout: 30_000 });
  const inspect = () => canvas.evaluate(element => (element as HTMLCanvasElement & { inspectFuelLevel: () => FuelInspection }).inspectFuelLevel());
  const pixels = () => canvas.evaluate(element => (element as HTMLCanvasElement & { inspectGolf: (pixels: boolean) => { contrastPixels: number } }).inspectGolf(true).contrastPixels);
  await page.getByRole('button', { name: 'Combustivel', exact: true }).click();
  await page.getByRole('button', { name: 'Pausar motor', exact: true }).click();
  await page.getByRole('combobox', { name: 'Estado de operacao', exact: true }).selectOption('key');
  const view = page.getByRole('combobox', { name: 'Vista do nivel de combustivel' });
  const level = page.getByRole('slider', { name: 'Nivel no tanque', exact: true });
  const fault = page.getByRole('combobox', { name: 'Falha do sensor de nivel' });
  const advance = page.getByRole('button', { name: 'Avancar leitura 1 s', exact: true });
  const settle = async () => { for (let step = 0; step < 5; step += 1) await advance.click(); };
  await expect.poll(async () => (await inspect()).wires.length).toBe(4);
  const initial = await inspect();
  expect(initial.wires[0].from).toEqual([-250, 475, 2165]);
  expect(initial.wires[0].to).toEqual([-390, 915, 875]);
  for (const coordinate of initial.projected.flat()) expect(Math.abs(coordinate)).toBeLessThan(1);
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  expect(await pixels()).toBeGreaterThan(100);
  await lab.screenshot({ path: testInfo.outputPath('fuel-circuit.png') });
  await view.selectOption('tank');
  await level.focus(); await level.press('Home');
  await expect.poll(async () => (await inspect()).floatPosition[1]).toBeCloseTo(325);
  expect((await inspect()).liquidSurface).toBe(325);
  expect((await inspect()).senderOhms).toBe(280);
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  await canvas.screenshot({ path: testInfo.outputPath('fuel-empty-tank.png') });
  await level.focus(); await level.press('End');
  await expect.poll(async () => (await inspect()).floatPosition[1]).toBeCloseTo(585);
  expect((await inspect()).liquidSurface).toBe(585);
  expect((await inspect()).senderOhms).toBe(40);
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  expect(await pixels()).toBeGreaterThan(100);
  await canvas.screenshot({ path: testInfo.outputPath('fuel-full-tank.png') });
  await view.selectOption('sender');
  await expect.poll(async () => (await inspect()).projected.every(point => point.every(coordinate => Math.abs(coordinate) < 1))).toBe(true);
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  expect(await pixels()).toBeGreaterThan(100);
  await canvas.screenshot({ path: testInfo.outputPath('fuel-sender.png') });
  await view.selectOption('gauge');
  const held = (await inspect()).indicated;
  expect(held).toBe(initial.indicated);
  await advance.click();
  expect((await inspect()).indicated).toBeGreaterThan(held);
  expect((await inspect()).indicated).toBeLessThan(1);
  await settle();
  await expect.poll(async () => (await inspect()).needleRotation).toBeLessThan(-1.2);
  const full = await inspect();
  expect(full.engineAngle).toBe(initial.engineAngle);
  expect(full.temperature).toBe(initial.temperature);
  expect(full.wipersElapsed).toBe(initial.wipersElapsed);
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  expect(await pixels()).toBeGreaterThan(100);
  await canvas.screenshot({ path: testInfo.outputPath('fuel-gauge-full.png') });
  await level.focus(); await level.press('Home');
  await settle();
  expect((await inspect()).reserveLamp).toBe(true);
  expect((await inspect()).faultLamp).toBe(false);
  await expect.poll(async () => (await inspect()).needleRotation).toBeGreaterThan(1.2);
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  await canvas.screenshot({ path: testInfo.outputPath('fuel-gauge-reserve.png') });

  for (const failure of ['signal-open', 'ground-open', 'short-ground']) {
    await fault.selectOption(failure);
    const failed = await inspect();
    expect(failed.decoded).toBeNull(); expect(failed.faultLamp).toBe(true); expect(failed.reserveLamp).toBe(false);
    expect(failed.voltage).toBe(failure === 'short-ground' ? 0 : 5);
  }
  await page.getByRole('combobox', { name: 'Estado de operacao', exact: true }).selectOption('idle');
  expect((await inspect()).pumpPowered).toBe(true);
  await fault.selectOption('none');
  await fault.selectOption('float-stuck');
  await level.focus(); await level.press('End');
  expect((await inspect()).level).toBe(1);
  expect((await inspect()).floatLevel).toBe(0);
  expect((await inspect()).decoded).toBeCloseTo(0);
  expect((await inspect()).faultLamp).toBe(false);
  await view.selectOption('tank');
  await expect.poll(async () => (await inspect()).floatPosition[1]).toBeCloseTo(325);
  expect((await inspect()).liquidSurface).toBe(585);
  await fault.selectOption('none');
  await expect.poll(async () => (await inspect()).floatPosition[1]).toBeCloseTo(585);
  await view.selectOption('gauge');
  const fuse = page.getByRole('checkbox', { name: 'Fusivel do instrumento aberto' });
  await fuse.check();
  expect((await inspect()).supply).toBe(false);
  expect((await inspect()).currentMa).toBe(0);
  expect((await inspect()).pumpPowered).toBe(true);
  await fuse.uncheck();
  await page.getByRole('combobox', { name: 'Estado de operacao', exact: true }).selectOption('off');
  expect((await inspect()).level).toBe(1);
  expect((await inspect()).supply).toBe(false);
  await page.getByRole('combobox', { name: 'Estado de operacao', exact: true }).selectOption('key');
  expect((await inspect()).supply).toBe(true);
  await page.getByRole('button', { name: 'Rodar motor', exact: true }).click();
  const moving = (await inspect()).indicated;
  await expect.poll(async () => (await inspect()).indicated).toBeGreaterThan(moving);
  await page.getByRole('button', { name: 'Pausar motor', exact: true }).click();
  const paused = await inspect();
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  await canvas.screenshot({ path: testInfo.outputPath('fuel-gauge-recovered.png') });
  expect((await inspect()).elapsed).toBe(paused.elapsed);
  await level.scrollIntoViewIfNeeded();
  expect(await level.evaluate(element => { const bounds = element.getBoundingClientRect(); return document.elementFromPoint(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2) === element; })).toBe(true);
  await page.locator('.golf-inspector').screenshot({ path: testInfo.outputPath('fuel-controls.png') });
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  const camera = (await inspect()).camera;
  const bounds = (await canvas.boundingBox())!;
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2); await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width * 0.6, bounds.y + bounds.height * 0.6, { steps: 8 }); await page.mouse.up();
  await expect.poll(async () => (await inspect()).camera).not.toEqual(camera);
  expect(await pixels()).toBeGreaterThan(100);
  await page.getByRole('button', { name: 'Restaurar enquadramento', exact: true }).click();
  await expect.poll(async () => (await inspect()).projected.every(point => point.every(coordinate => Math.abs(coordinate) < 1))).toBe(true);
  const retained = await inspect();
  await page.getByRole('button', { name: 'Montagem', exact: true }).click();
  await expect(lab).toHaveAttribute('data-fuel-focus', 'none');
  await expect.poll(async () => (await inspect()).wires.length, { timeout: 30_000 }).toBe(4);
  expect((await inspect()).level).toBe(retained.level);
  expect((await inspect()).indicated).toBe(retained.indicated);
  await expect.poll(async () => (await inspect()).needleRotation, { timeout: 30_000 }).toBeCloseTo(-(retained.indicated - 0.5) * Math.PI * 0.8);
  await page.getByRole('button', { name: 'Combustivel', exact: true }).click();
  expect((await inspect()).elapsed).toBe(retained.elapsed);
  await page.getByRole('button', { name: 'Reiniciar sensor', exact: true }).click();
  expect((await inspect()).indicated).toBe(1);
  expect(await lab.evaluate(element => { const bounds = element.getBoundingClientRect(); return Array.from(element.querySelectorAll('.golf-toolbar, .golf-workspace, .golf-transport')).every(row => row.getBoundingClientRect().right <= bounds.right + 1 && row.getBoundingClientRect().left >= bounds.left - 1); })).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});