import { expect, test } from '@playwright/test';

interface WiperInspection {
  mode: string; phase: number; armPhase: number; cycles: number; elapsed: number; engineAngle: number;
  motorPowered: boolean; cyclesPerMinute: number; parkContact: boolean; washerPowered: boolean; afterWash: number;
  camera: number[]; projected: number[][]; stalkPoint: number[]; stalkAngle: number;
  washerPoint: number[];
  arms: { rotation: number; tip: number[] }[];
  links: { length: number; visible: boolean; ends: number[][] }[];
  wires: string[];
}

test('Limpadores: comando eletrico mecanismo repouso e falhas', async ({ page }, testInfo) => {
  test.setTimeout(180_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/courses/injecao-eletronica-40h/lessons/aula-5-motor-completo');
  const lab = page.locator('.golf-lab');
  const canvas = page.locator('canvas[data-golf-canvas]');
  await expect(canvas).toBeVisible({ timeout: 30_000 });
  const inspect = () => canvas.evaluate(element => (element as HTMLCanvasElement & { inspectWipers: () => WiperInspection }).inspectWipers());
  const pixels = () => canvas.evaluate(element => (element as HTMLCanvasElement & { inspectGolf: (pixels: boolean) => { contrastPixels: number } }).inspectGolf(true).contrastPixels);
  await page.getByRole('button', { name: 'Limpadores', exact: true }).click();
  await page.getByRole('button', { name: 'Pausar motor', exact: true }).click();
  await page.getByRole('combobox', { name: 'Estado de operacao', exact: true }).selectOption('key');
  const mode = page.getByRole('combobox', { name: 'Modo dos limpadores' });
  const view = page.getByRole('combobox', { name: 'Vista dos limpadores' });
  const fault = page.getByRole('combobox', { name: 'Falha dos limpadores' });
  const step = page.getByRole('button', { name: 'Avancar 0,25 s', exact: true });
  const reset = page.getByRole('button', { name: 'Reiniciar limpadores', exact: true });
  await expect.poll(async () => (await inspect()).wires.length).toBe(6);
  expect((await inspect()).washerPoint).toEqual([525, 475, -470]);
  expect((await inspect()).motorPowered).toBe(false);
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  expect(await pixels()).toBeGreaterThan(100);
  await lab.screenshot({ path: testInfo.outputPath('wipers-circuit.png') });
  await view.selectOption('stalk');
  await expect.poll(async () => (await inspect()).projected.every(point => point.every(coordinate => Math.abs(coordinate) < 1))).toBe(true);
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  const point = (await inspect()).stalkPoint;
  const stalkBounds = (await canvas.boundingBox())!;
  await page.mouse.click(stalkBounds.x + (point[0] + 1) * stalkBounds.width / 2, stalkBounds.y + (1 - point[1]) * stalkBounds.height / 2);
  await expect(mode).toHaveValue('intermittent');
  await expect.poll(async () => (await inspect()).stalkAngle).toBeCloseTo(0.16);
  await canvas.screenshot({ path: testInfo.outputPath('wipers-stalk.png') });
  await view.selectOption('mechanism');
  await mode.selectOption('low');
  const parked = await inspect();
  expect(parked.cyclesPerMinute).toBe(40);
  for (let index = 0; index < 6; index += 1) {
    await step.click();
    await expect.poll(async () => (await inspect()).links.map(link => Math.round(link.length))).toEqual([60, 250, 100, 100, 680]);
    const current = await inspect();
    expect(current.engineAngle).toBe(parked.engineAngle);
    expect(current.arms[0].rotation).toBeCloseTo(current.arms[1].rotation);
    const joints = [[0, 1, 1, 0], [1, 1, 2, 1], [2, 1, 4, 0], [4, 1, 3, 1]];
    for (const [first, firstEnd, second, secondEnd] of joints) expect(Math.hypot(...current.links[first].ends[firstEnd].map((value, axis) => value - current.links[second].ends[secondEnd][axis]))).toBeLessThan(1e-6);
    for (const coordinate of current.projected.flat()) expect(Math.abs(coordinate)).toBeLessThan(1);
    if (index === 2) {
      expect(current.arms[0].rotation).toBeGreaterThan(0.5);
      await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
      expect(await pixels()).toBeGreaterThan(100);
      await canvas.screenshot({ path: testInfo.outputPath('wipers-sweep.png') });
    }
  }
  await mode.selectOption('high');
  expect((await inspect()).cyclesPerMinute).toBe(60);
  await step.click();
  await mode.selectOption('off');
  expect((await inspect()).motorPowered).toBe(true);
  for (let index = 0; index < 6; index += 1) await step.click();
  expect((await inspect()).phase).toBe(0);
  expect((await inspect()).motorPowered).toBe(false);
  await mode.selectOption('low');
  await page.getByRole('button', { name: 'Rodar motor', exact: true }).click();
  const active = await inspect();
  await expect.poll(async () => (await inspect()).phase).not.toBe(active.phase);
  await page.getByRole('button', { name: 'Pausar motor', exact: true }).click();
  const frozen = await inspect();
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  await canvas.screenshot({ path: testInfo.outputPath('wipers-paused.png') });
  expect((await inspect()).phase).toBe(frozen.phase);

  const fuse = page.getByRole('checkbox', { name: 'Fusivel dos limpadores aberto' });
  await fuse.check();
  await step.click();
  expect((await inspect()).phase).toBe(frozen.phase);
  expect((await inspect()).motorPowered).toBe(false);
  await fuse.uncheck();
  await fault.selectOption('motor');
  await step.click();
  expect((await inspect()).phase).toBe(frozen.phase);
  await fault.selectOption('linkage');
  await step.click();
  expect((await inspect()).phase).not.toBe(frozen.phase);
  expect((await inspect()).armPhase).toBe(frozen.armPhase);
  await expect.poll(async () => (await inspect()).links[1].visible).toBe(false);
  await fault.selectOption('none');
  await step.click();
  expect((await inspect()).armPhase).toBe((await inspect()).phase);
  await reset.click();
  await fault.selectOption('park');
  await step.click();
  expect((await inspect()).motorPowered).toBe(true);
  expect((await inspect()).parkContact).toBe(false);
  const beforeKey = (await inspect()).phase;
  await page.getByRole('combobox', { name: 'Estado de operacao', exact: true }).selectOption('off');
  await step.click();
  expect((await inspect()).phase).toBe(beforeKey);
  expect((await inspect()).motorPowered).toBe(false);
  await page.getByRole('combobox', { name: 'Estado de operacao', exact: true }).selectOption('key');
  expect((await inspect()).phase).toBe(beforeKey);
  await reset.click();
  const wash = page.getByRole('checkbox', { name: 'Comando de lavagem', exact: true });
  await wash.check();
  await step.click();
  expect((await inspect()).washerPowered).toBe(true);
  await wash.uncheck();
  for (let index = 0; index < 12; index += 1) await step.click();
  expect((await inspect()).afterWash).toBe(0);
  expect((await inspect()).phase).toBe(0);
  await mode.selectOption('intermittent');
  for (let index = 0; index < 6; index += 1) await step.click();
  const waiting = await inspect();
  expect(waiting.phase).toBe(0);
  await step.click();
  expect((await inspect()).cycles).toBe(waiting.cycles);
  await mode.scrollIntoViewIfNeeded();
  expect(await mode.evaluate(element => { const bounds = element.getBoundingClientRect(); return document.elementFromPoint(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2) === element; })).toBe(true);
  await page.locator('.golf-inspector').screenshot({ path: testInfo.outputPath('wipers-controls.png') });
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  const camera = (await inspect()).camera;
  const bounds = (await canvas.boundingBox())!;
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width * 0.6, bounds.y + bounds.height * 0.6, { steps: 8 });
  await page.mouse.up();
  await expect.poll(async () => (await inspect()).camera).not.toEqual(camera);
  expect(await pixels()).toBeGreaterThan(100);
  await page.getByRole('button', { name: 'Restaurar enquadramento', exact: true }).click();
  await expect.poll(async () => (await inspect()).projected.every(point => point.every(coordinate => Math.abs(coordinate) < 1))).toBe(true);
  const retained = await inspect();
  await page.getByRole('button', { name: 'Montagem', exact: true }).click();
  await expect(lab).toHaveAttribute('data-wiper-focus', 'none');
  expect((await inspect()).phase).toBe(retained.phase);
  expect((await inspect()).mode).toBe(retained.mode);
  await expect.poll(async () => (await inspect()).wires.length, { timeout: 30_000 }).toBe(6);
  await page.getByRole('button', { name: 'Limpadores', exact: true }).click();
  expect((await inspect()).elapsed).toBe(retained.elapsed);
  expect(await lab.evaluate(element => { const bounds = element.getBoundingClientRect(); return Array.from(element.querySelectorAll('.golf-toolbar, .golf-workspace, .golf-transport')).every(row => row.getBoundingClientRect().right <= bounds.right + 1 && row.getBoundingClientRect().left >= bounds.left - 1); })).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});