import { expect, test } from '@playwright/test';

interface CoolingInspection {
  temperature: number; radiatorC: number; elapsed: number; angle: number;
  thermostat: number; pumpLpm: number; radiatorLpm: number; heaterLpm: number; bypassLpm: number;
  fanPowered: boolean; fanRotation: number; pumpRotation: number; valveLift: number;
  heatInputW: number; warning: string; camera: number[]; projected: number[][];
  markers: { name: string; visible: boolean; flowLpm: number; position: number[] }[];
}

test('Arrefecimento: circuito termico falhas animacao e estado compartilhado', async ({ page }, testInfo) => {
  test.setTimeout(180_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/courses/injecao-eletronica-40h/lessons/aula-5-motor-completo');
  const lab = page.locator('.golf-lab');
  const canvas = page.locator('canvas[data-golf-canvas]');
  await expect(canvas).toBeVisible({ timeout: 30_000 });
  const inspect = () => canvas.evaluate(element => (element as HTMLCanvasElement & { inspectCooling: () => CoolingInspection }).inspectCooling());
  const pixels = () => canvas.evaluate(element => (element as HTMLCanvasElement & { inspectGolf: (pixels: boolean) => { contrastPixels: number } }).inspectGolf(true).contrastPixels);
  await page.getByRole('button', { name: 'Arrefecimento', exact: true }).click();
  await expect(lab).toHaveAttribute('data-cooling-focus', 'true');
  await page.getByRole('button', { name: 'Pausar motor', exact: true }).click();
  await page.getByRole('combobox', { name: 'Estado de operacao', exact: true }).selectOption('idle');
  const cold = page.getByRole('button', { name: 'Ensaio frio', exact: true });
  const hot = page.getByRole('button', { name: 'Ensaio quente', exact: true });
  const advance = page.getByRole('button', { name: 'Avancar 60 s termicos', exact: true });
  const fault = page.getByRole('combobox', { name: 'Falha de arrefecimento' });
  await cold.click();
  await expect.poll(async () => (await inspect()).markers.length).toBe(12);
  const initial = await inspect();
  expect(initial.temperature).toBe(20);
  expect(initial.thermostat).toBe(0);
  expect(initial.radiatorLpm).toBe(0);
  expect(initial.bypassLpm).toBeGreaterThan(0);
  await expect.poll(async () => (await inspect()).valveLift).toBe(0);
  for (const coordinate of initial.projected.flat()) expect(Math.abs(coordinate)).toBeLessThan(1);
  expect(await pixels()).toBeGreaterThan(100);
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  await lab.screenshot({ path: testInfo.outputPath('cooling-cold.png') });
  await advance.click();
  const warmed = await inspect();
  expect(warmed.temperature).toBeGreaterThan(20);
  expect(warmed.angle).toBe(initial.angle);
  expect(warmed.elapsed).toBeCloseTo(60);
  await expect.poll(async () => (await inspect()).pumpRotation).toBeGreaterThan(initial.pumpRotation);

  await hot.click();
  await expect.poll(async () => (await inspect()).valveLift).toBe(18);
  expect((await inspect()).fanPowered).toBe(true);
  for (const focus of ['thermostat', 'pump', 'radiator']) {
    await page.getByRole('combobox', { name: 'Vista do arrefecimento' }).selectOption(focus);
    await expect.poll(async () => (await inspect()).projected.every(point => point.every(coordinate => Math.abs(coordinate) < 1))).toBe(true);
    expect(await pixels()).toBeGreaterThan(100);
    await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
    await canvas.screenshot({ path: testInfo.outputPath(`cooling-${focus}.png`) });
  }
  await page.getByRole('combobox', { name: 'Vista do arrefecimento' }).selectOption('circuit');
  await page.getByRole('button', { name: 'Rodar motor', exact: true }).click();
  const moving = await inspect();
  await expect.poll(async () => (await inspect()).fanRotation).toBeGreaterThan(moving.fanRotation);
  await expect.poll(async () => (await inspect()).markers).not.toEqual(moving.markers);
  await page.getByRole('button', { name: 'Pausar motor', exact: true }).click();
  const paused = await inspect();
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  await lab.screenshot({ path: testInfo.outputPath('cooling-hot.png') });
  expect((await inspect()).elapsed).toBe(paused.elapsed);
  expect((await inspect()).fanRotation).toBe(paused.fanRotation);

  const fuse = page.getByRole('checkbox', { name: 'Fusivel da ventoinha aberto' });
  await fuse.check();
  expect((await inspect()).fanPowered).toBe(false);
  const stopped = (await inspect()).fanRotation;
  await advance.click();
  expect((await inspect()).fanRotation).toBe(stopped);
  await fuse.uncheck();
  await fault.selectOption('fan');
  expect((await inspect()).fanPowered).toBe(false);
  await fault.selectOption('none');
  const beforeKey = (await inspect()).temperature;
  await page.getByRole('combobox', { name: 'Estado de operacao', exact: true }).selectOption('off');
  expect((await inspect()).temperature).toBe(beforeKey);
  expect((await inspect()).pumpLpm).toBe(0);
  expect((await inspect()).fanPowered).toBe(false);
  expect((await inspect()).heatInputW).toBe(0);
  await page.getByRole('combobox', { name: 'Estado de operacao', exact: true }).selectOption('idle');
  expect((await inspect()).temperature).toBe(beforeKey);
  await hot.click();
  await fault.selectOption('pump');
  const pumpStopped = (await inspect()).pumpRotation;
  await advance.click();
  await expect.poll(async () => (await inspect()).markers.every(marker => !marker.visible)).toBe(true);
  expect((await inspect()).pumpLpm).toBe(0);
  expect((await inspect()).pumpRotation).toBe(pumpStopped);
  expect((await inspect()).temperature).toBeGreaterThan(110);
  await hot.click();
  await fault.selectOption('thermostat-closed');
  await expect.poll(async () => (await inspect()).valveLift).toBe(0);
  for (let step = 0; step < 3; step += 1) await advance.click();
  expect((await inspect()).warning).toBe('overheat');
  expect((await inspect()).radiatorLpm).toBe(0);
  await cold.click();
  await fault.selectOption('thermostat-open');
  await expect.poll(async () => (await inspect()).valveLift).toBe(18);
  expect((await inspect()).radiatorLpm).toBeGreaterThan(0);
  await hot.click();
  const airflow = page.getByRole('slider', { name: 'Ar frontal equivalente', exact: true });
  await airflow.scrollIntoViewIfNeeded();
  expect(await airflow.evaluate(element => {
    const bounds = element.getBoundingClientRect();
    return document.elementFromPoint(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2) === element;
  })).toBe(true);
  await airflow.focus(); await airflow.press('End');
  await page.getByRole('checkbox', { name: 'Aquecedor da cabine', exact: true }).check();
  await advance.click();
  expect((await inspect()).temperature).toBeLessThan(110);
  await page.locator('.golf-inspector').screenshot({ path: testInfo.outputPath('cooling-controls.png') });
  await lab.evaluate(element => element.scrollIntoView({ block: 'start' }));
  const originalCamera = (await inspect()).camera;
  const bounds = (await canvas.boundingBox())!;
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width * 0.6, bounds.y + bounds.height * 0.6, { steps: 8 });
  await page.mouse.up();
  await expect.poll(async () => (await inspect()).camera).not.toEqual(originalCamera);
  expect(await pixels()).toBeGreaterThan(100);
  await canvas.screenshot({ path: testInfo.outputPath('cooling-orbit.png') });
  await page.getByRole('button', { name: 'Restaurar enquadramento', exact: true }).click();
  await expect.poll(async () => (await inspect()).projected.every(point => point.every(coordinate => Math.abs(coordinate) < 1))).toBe(true);
  const retained = await inspect();
  await page.getByRole('button', { name: 'Montagem', exact: true }).click();
  await expect(lab).toHaveAttribute('data-cooling-focus', 'false');
  expect((await inspect()).temperature).toBe(retained.temperature);
  expect((await inspect()).elapsed).toBe(retained.elapsed);
  await page.getByRole('button', { name: 'Arrefecimento', exact: true }).click();
  expect((await inspect()).temperature).toBe(retained.temperature);
  expect(await lab.evaluate(element => {
    const bounds = element.getBoundingClientRect();
    return Array.from(element.querySelectorAll('.golf-toolbar, .golf-workspace, .golf-transport')).every(row => row.getBoundingClientRect().right <= bounds.right + 1 && row.getBoundingClientRect().left >= bounds.left - 1);
  })).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});